name: Client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/client

    strategy:
      matrix:
        node-version: [16.6.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup PNPM
      run: npm install -g pnpm
    - name: Setup NodeJS with PNPM caching
      uses: actions/setup-node@v2
      with:
        node-version: "16.6.0"
        cache: pnpm
    - run: pnpm install
    - run: npm run build
      env:
        CI: true
